name: Deploy API and Extract Swagger

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment (dev, qa, prod)'
        required: true
        type: choice
        options:
          - dev
          - qa
          - prod
        default: dev

jobs:
  call-extract-apis:
    uses: ./path/to/extract-swagger-apis.yml
    with:
      environment: ${{ github.event.inputs.environment }}
