name: Extract APIs from Swagger

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up .NET SDK (for building the project)
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      # 3. Restore the .NET project dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build the .NET project
      - name: Build the .NET project
        run: dotnet build --no-restore

      # 5. Run the .NET application to serve Swagger (in the background)
      - name: Start .NET API and Swagger
        run: |
          nohup dotnet run --urls "http://0.0.0.0:5001" &

      # 6. Install necessary dependencies (for extracting APIs from Swagger JSON)
      - name: Set up Python and install dependencies
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml

      # 7. Extract Swagger APIs based on environments (dev, qa, prod)
      - name: Download and split Swagger JSON
        run: |
          python3 Scripts/split_openapi.py dev
          python3 Scripts/split_openapi.py qa
          python3 Scripts/split_openapi.py prod

      # 8. Upload the generated YAML files as artifacts
      - name: Upload API YAML artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-yaml-files
          path: output/*.yaml
