name: Build & Split Swagger by Environment

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, qa, pt]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore MyApi.csproj

    - name: Build project
      run: dotnet build MyApi.csproj --configuration Release

    - name: Publish project
      run: dotnet publish MyApi.csproj --configuration Release -o ./out

    - name: Run Web API (background)
      run: |
        nohup dotnet ./out/MyApi.dll --environment ${{ matrix.env }} &
        sleep 10

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python packages
      run: pip install pyyaml requests

    - name: Download & Split Swagger YAML
      run: python Scripts/split_openapi.py ${{ matrix.env }}

    - name: Upload split YAMLs as artifact
      uses: actions/upload-artifact@v3
      with:
        name: swagger-${{ matrix.env }}
        path: output/${{ matrix.env }}
