name: Build and Split Swagger (Local)

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-process:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [dev, qa, pt]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Publish project
      run: dotnet publish --configuration Release -o ./out

    - name: Run API locally (in background)
      run: |
        nohup dotnet ./out/MyApi.dll --environment ${{ matrix.env }} > api.log 2>&1 &
        sleep 10

    - name: Print API Logs (for debugging)
      run: cat api.log || true

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python packages
      run: pip install requests pyyaml

    - name: Download Swagger and Split
      run: python Scripts/split_openapi.py ${{ matrix.env }}

    - name: Upload split YAMLs
      uses: actions/upload-artifact@v3
      with:
        name: swagger-${{ matrix.env }}
        path: output/${{ matrix.env }}
