name: Generate Swagger and Split YAMLs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Choose environment (dev, qa, pt)"
        required: true
        default: "dev"

jobs:
  call-swagger-workflow:
    uses: ./.github/workflows/reusable-swagger.yml
    with:
      environment: ${{ github.event.inputs.environment }}
